Create backup restore section for Apache Cassandra
bitnami/charts-docs pull request #12
Opened 2021-03-05 13:43 UTC by raquel-campuzano

New section on Apache Cassandra documentation to explain how to backup and restore deployments on Kubernetes.

2021-03-05 13:46 UTC, vikram-bitnami commented on charts/cassandra/_backup_restore.md.erb
> +* Use Velero to back up  the PersistentVolumes (PVs) used by the Apache Cassandra deployment on the source cluster.
extra space between up and the

2021-03-08 13:59 UTC, raquel-campuzano commented on charts/mongodb/_backup_restore.md.erb
> +Refer to our detailed [tutorial on backing up and restoring Bitnami MongoDB chart deployments on Kubernetes](https://docs.bitnami.com/tutorials/backup-restore-data-mongodb-galera-kubernetes/), which
Remove "galera" from the tutorial link

2021-03-08 14:07 UTC, vikram-bitnami commented on charts/mongodb/_backup_restore.md.erb
> +Refer to our detailed [tutorial on backing up and restoring Bitnami MongoDB chart deployments on Kubernetes](https://docs.bitnami.com/tutorials/backup-restore-data-mongodb-galera-kubernetes/), which
Correct link is https://docs.bitnami.com/tutorials/backup-restore-data-mongodb-kubernetes/

2021-03-08 14:08 UTC, vikram-bitnami commented on charts/postgresql/_backup_restore.md.erb
> +title: Backup and restore the deployment
Backup and restore PostgreSQL deployments -> to be consistent with other titles

2021-03-08 14:08 UTC, vikram-bitnami commented on charts/postgresql/_backup_restore.md.erb
> +To back up and restore Bitnami PostgreSQL Cassandra Helm chart deployments on Kubernetes, you need to back up the persistent volumes from the source deployment and attach them to a new deployment usi
PostgreSQL Cassandra is incorrect

2021-03-08 14:09 UTC, vikram-bitnami commented on charts/redis-cluster/_backup_restore.md.erb
> +These are the steps you will usually follow to back up and restore your Apache Cassandra database cluster data:
Cassandra?

2021-03-09 10:40 UTC, vikram-bitnami requested changes

2021-03-09 10:40 UTC, vikram-bitnami commented on charts/mongodb/_backup_restore.md.erb
> +* Restore the data using the *mongostore* tool to import the backup to the new cluster.
mongorestore

2021-03-09 10:40 UTC, vikram-bitnami commented on charts/cassandra/_backup_restore.md.erb
> +title: Backup and restore the deployment
The titles should be consistent for all the sections. Some are using the name of the chart and others aren't.

2021-03-09 10:40 UTC, vikram-bitnami commented on charts/_backup_restore.md.erb
> +title: Backup and restore the deployment
In this case I think we cannot put the chart name as this is a generic section but see my comment for the other more specific section titles.

2021-03-09 13:20 UTC, marcosbc requested changes
Small requests, I'm not that familiar with this project so let me know if some of them don't make sense!

2021-03-09 13:20 UTC, marcosbc commented on charts/_backup_restore.md.erb
> +To back up and restore Bitnami Helm chart deployments on Kubernetes, you need to back up the persistent volumes from the source deployment and attach them to a new deployment using [Velero](https://v
It sounds like Velero is a requirement? Maybe we should let the user know it is only one of the ways to make backups, and it's the one we have documented.

2021-03-09 13:20 UTC, marcosbc commented on charts/mariadb-galera/_backup_restore.md.erb
> +### Method 2: Back up and restore persistent data volumes
I would add "with Velero" in the header as there are many ways to backup persistent volumes (i.e. see above). Also in the files below.

2021-03-09 13:20 UTC, marcosbc commented on charts/mongodb/_backup_restore.md.erb
> +* Back up the persistent volumes from the source deployment and attach them to a new deployment using Velero, a Kubernetes backup/restore tool.
Why is this weird spacing between the bullet lists?

2021-03-09 13:20 UTC, marcosbc commented on charts/postgresql/_backup_restore.md.erb
> +* Create a new PostgreSQL deployment on the destination cluster with the same deployment name, credentials and other parameters as the original. This new deployment will use the restored PVs and henc
If this section is going to be exactly the same in many locations, maybe it would be worth it to create a partial

2021-03-10 12:18 UTC, vikram-bitnami commented on charts/postgresql/_backup_restore.md.erb
> +* Create a new PostgreSQL deployment on the destination cluster with the same deployment name, credentials and other parameters as the original. This new deployment will use the restored PVs and henc
Yes it's a good idea but I think in this case the partial should only contain the 4 bullet points written in a generic way (without naming any chart) such as

```

* Install Velero on the source and destination clusters.
* Use Velero to back up  the PersistentVolumes (PVs) used by the deployment on the source cluster.
* Use Velero to restore the backed-up PVs on the destination cluster.
* Create a new deployment on the destination cluster with the same chart,  deployment name, credentials and other parameters as the original. This new deployment will use the restored PVs and hence the original data.
```

This allows us to have a few customized sentences before/after the common partial where we can add anything specific to the chart.

2021-03-12 09:36 UTC, marcosbc approved these changes
LGTM! 👍

2021-03-12 09:56 UTC, vikram-bitnami approved these changes
Approving, please make the changes noted if possible

2021-03-12 09:56 UTC, vikram-bitnami commented on charts/_backup_restore.md.erb
> +<%= partial ‘platforms/kubernetes/charts/backup_restore_pv_velero.md.erb’ %>
Any reason to use a tick quote/smart quote ` here instead of the usual single-quote ' for file links? I guess it works but to avoid any issues later, could you change to use single-quote in all files? (some files already use single quote, others use tick quote).

2021-03-12 09:56 UTC, vikram-bitnami commented on charts/cassandra/_backup_restore.md.erb
> +<%= partial ‘platforms/kubernetes/charts/backup_restore_pv_velero.md.erb’ %>
Replace with single quote

2021-03-12 09:56 UTC, vikram-bitnami commented on charts/mariadb-galera/_backup_restore.md.erb
> +### Method 2: Back up and restore persistent data volumes
I think this is pending? Should be done for all cases.

2021-03-12 10:30 UTC, raquel-campuzano commented on charts/_backup_restore.md.erb
> +<%= partial ‘platforms/kubernetes/charts/backup_restore_pv_velero.md.erb’ %>
No reasons. I think that this was an issue with the text editor.

2021-03-12 10:30 UTC, merged