Asp docs - Add new sections and fix some from other charts
bitnami/charts-docs pull request #14
Opened 2021-03-19 11:45 UTC by raquel-campuzano

2021-03-19 14:51 UTC, vikram-bitnami requested changes

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/apache/_deploy_custom_app.md.erb
> +<%
Looks like there is something wrong here, this is an apache section in an asp.net diff, plus this section is already present and published including some edits: https://docs.bitnami.com/kubernetes/infrastructure/apache/get-started/deploy-custom-application/

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_chart_persistence.md.erb
> +id: chart_persistence
This id was changed recently, could you use the id that is also used in the Apache/WordPress/mySQL/MariaDB charts? 

(BTW, those chart docs metadata and content should be the reference for new sections as they were all updated as part of a second round of improvements.)

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_add_environment_variables.md.erb
> +In case you want to add extra environment variables, you can use the *extraEnvVars* property.
To add..., use the...

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_add_environment_variables.md.erb
> +Alternatively, you can use a ConfigMap or a Secret with the environment variables. To do so, use the *extraEnvVarsCM* or the *extraEnvVarsSecret* values.
Alternatively, use a ...

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_deploy_custom_app.md.erb
> +* Cloning your ASP.NET Core application code from a GIT repository.
Git

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_deploy_custom_app.md.erb
> +* Using a Docker image containing your ASP.NET Core application ready to be executed.
application.

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_deploy_custom_app.md.erb
> +### Cloning your ASP.NET Core application code from a GIT repository
Git

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_extra_containers.md.erb
> +title: Extra Containers
Should begin with a verb

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_extra_containers.md.erb
> +id: extra_containers
should begin with a verb following other section titles/ids

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_extra_containers.md.erb
> +If you have a need for additional containers to run within the same pod as the ASP.NET Core app (e.g. an additional metrics or logging exporter), you can do so via the *sidecars* configuration parame
To run additional containers within, ... use the sidecars...

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_extra_containers.md.erb
> +Similarly, you can add extra init containers using the initContainers parameter.
add extra

*initContainers*

Could you please check and format with italics for all chart parameters in other sections as well?

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_extra_containers.md.erb
> +There are cases where you may want to deploy extra objects, such a ConfigMap containing your app's configuration or some extra deployment with a micro service used by your app For covering this case,
app -> application - should be changed in all cases.

Missing full stop before For 

For covering -> For

it will mount it -> could you clarify the two "it", not clear if you refer to the ConfigMap, the app or the app configuration.

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_ingress.md.erb
> +This chart provides support for ingress resources. If you have an ingress controller installed on your cluster, such as [nginx-ingress](https://hub.kubeapps.com/charts/stable/nginx-ingress) or [traef
Should be Ingress in all cases, except for the chart names/chart parameters.

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/aspnet-core/_ingress.md.erb
> +platforms: kubernetes
There is a section in the WordPress chart https://docs.bitnami.com/kubernetes/apps/wordpress/configuration/configure-use-ingress/ which seems to have very similar content. Can we make a partial and reuse?

2021-03-19 14:51 UTC, vikram-bitnami commented on charts/consul/_ingress.md.erb
Consul section in ASP diff, is this part of the diff or accidental?

In any case, please see if a common Ingress section can be made/reused as per previous comment?

2021-03-22 08:34 UTC, juan131 requested changes

2021-03-22 08:34 UTC, juan131 commented on charts/aspnet-core/_add_environment_variables.md.erb
> +kong:
`kong`? This should refer to ASP.NET

2021-03-22 08:34 UTC, juan131 commented on charts/aspnet-core/_deploy_custom_app.md.erb
> +You can build your own Docker image containing your ASP.NET Core application ready to be executed. To do so, overwrite the default image setting the image.* parameters, and set your custom command an
```suggestion
You can build your own Docker image containing your ASP.NET Core application ready to be executed. To do so, overwrite the default image setting the image.* parameters, and set your custom command and arguments setting the *command* and *args* parameters:
```

2021-03-22 08:34 UTC, juan131 commented on charts/aspnet-core/_deploy_custom_app.md.erb
> +  To use this feature, set the *appFromExternalRepo.enabled* to true and set the repository and branch to use setting the *appFromExternalRepo.clone.repository* and *appFromExternalRepo.clone.revisio
Use `*true*` instead of `true`:
```suggestion
To use this feature, set the *appFromExternalRepo.enabled* to *true* and set the repository and branch to use setting the *appFromExternalRepo.clone.repository* and *appFromExternalRepo.clone.revision* parameters. Then, specify the sub folder under the Git repository containing the ASP.NET Core app setting the *appFromExternalRepo.publish.subFolder* parameter. Finally, provide the start command to use setting the *appFromExternalRepo.startCommand*.
```

2021-03-22 08:34 UTC, juan131 commented on charts/aspnet-core/_deploy_custom_app.md.erb
> +If you previously created a PVC with your application code ready to be executed, you can mount it in the ASP.NET Core container setting the *appFromExistingPVC.enabled* parameter to true. Then, speci
Use `*true*` instead of `true`:
```suggestion
If you previously created a PVC with your application code ready to be executed, you can mount it in the ASP.NET Core container setting the *appFromExistingPVC.enabled* parameter to *true*. Then, specify the name of your existing PVC setting the *appFromExistingPVC.existingClaim* parameter.
```

2021-03-23 15:14 UTC, raquel-campuzano commented on charts/apache/_deploy_custom_app.md.erb
> +<%
When I was comparing files to get ids and so on, I found some files with errors as happened with some Apache files. I decided to fix them at the same time as I created the ASP. NET new sections.

2021-03-23 15:28 UTC, raquel-campuzano commented on charts/aspnet-core/_chart_persistence.md.erb
> +id: chart_persistence
+1

2021-03-23 15:35 UTC, raquel-campuzano commented on charts/aspnet-core/_extra_containers.md.erb
> +There are cases where you may want to deploy extra objects, such a ConfigMap containing your app's configuration or some extra deployment with a micro service used by your app For covering this case,
> it will mount it -> could you clarify the two "it", not clear if you refer to the ConfigMap, the app or the app configuration.

TBH I don't know exactly since I am not the author of this content, I am just migrating it from GitHub to docs. How can I check who was the author?

2021-03-23 15:48 UTC, raquel-campuzano commented on charts/consul/_ingress.md.erb
Will create a partial in a different diff. I need to check in which cases we can place that partial. Thank you.

2021-03-23 15:51 UTC, raquel-campuzano commented on charts/aspnet-core/_add_environment_variables.md.erb
> +kong:
https://github.com/bitnami/charts/tree/master/bitnami/aspnet-core#adding-extra-environment-variables
🤷‍♀️

2021-03-23 15:58 UTC, juan131 commented on charts/aspnet-core/_add_environment_variables.md.erb
> +kong:
The perfect occasion to fix it

2021-03-24 09:46 UTC, juan131 commented on charts/aspnet-core/_add_environment_variables.md.erb
> +kong:
Not solved yet

2021-03-24 14:36 UTC, juan131 commented on charts/aspnet-core/_add_environment_variables.md.erb
> +~~~
Sorry, I should have warned you that in this case it's even simpler:
```suggestion

~~~
extraEnvVars:
  - name: LOG_LEVEL
    value: error
~~~
```

2021-03-26 11:40 UTC, merged