T39354- Improve postgresql docs
bitnami/charts-docs pull request #22
Opened 2021-04-07 11:29 UTC by raquel-campuzano

2021-04-08 07:12 UTC, alemorcuq requested changes
Thanks for the PR. Not all guides have a `highlight` value. Is that ok?

2021-04-08 07:12 UTC, alemorcuq commented on charts/postgresql/_customize_primary_replica_services.md.erb
> +This allows you to override the values in the top level service object so that the primary and read can be of different service types and with different clusterIPs / nodePorts. Also in the case you w
I think I would say `read replica` instead of just `read`. Although I think PostgreSQL has a specific word for this nodes (standby), it looks like we use read replicas instead in our chart.

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_customize_primary_replica_services.md.erb
> +At the top level, there is a service object which defines the services for both primary and readReplicas. For deeper customization, there are service objects for both the primary and read types indiv
read replicas

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_customize_primary_replica_services.md.erb
> +title: Customize primary and read replica services in a replicated configuration
I think this title could be shorter eg. Customize replica services

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_enable_tls.md.erb
> +First, create the secret with the cetificates files:
cetificate -> typo

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_enable_tls.md.erb
> +First, create the secret with the cetificates files:
We can make this a list of two steps

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_enable_tls.md.erb
> +    $ kubectl create secret generic certificates-tls-secret --from-file=./cert.crt --from-file=./cert.key --from-file=./ca.crt
I guess we need to add a sentence above this to replace the certificate file paths with the correct paths for the user's system.

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_network_policy.md.erb
> +title: Enable the network policy
Reading through the content below, it seems like it could be rewritten in steps?

Also, there is a note which is not formatted correctly.

2021-04-08 07:50 UTC, vikram-bitnami commented on charts/postgresql/_configure_pod_affinity.md.erb
> +As an alternative, you can use of the preset configurations for pod affinity, pod anti-affinity, and node affinity available at the [bitnami/common](https://github.com/bitnami/charts/tree/master/bitn
use any of

2021-04-12 11:43 UTC, alemorcuq requested changes

2021-04-12 11:43 UTC, alemorcuq commented on charts/postgresql/_enable_tls.md.erb
> +First, create the secret with the certificates files. Remember to replace the certificate paths shown below with the paths where those certificates are located in your system
```suggestion
First, create the secret with the certificate files. Remember to replace the certificate paths shown below with the paths where those certificates are located in your system
```

2021-04-12 11:43 UTC, alemorcuq commented on charts/postgresql/_customize_replica_services.md.erb
> +At the top level, there is a service object which defines the services for both primary and read replicas. For deeper customization, there are service objects for both the primary and read types indi
```suggestion
At the top level, there is a service object which defines the services for both primary and read replicas. For deeper customization, there are service objects for both the primary and read replica types individually. 
```

2021-04-12 11:43 UTC, alemorcuq commented on charts/postgresql/_customize_replica_services.md.erb
> +This allows you to override the values in the top level service object so that the primary and read replicas can be of different service types and with different clusterIPs / nodePorts. Also in the c
```suggestion
This allows you to override the values in the top level service object so that the primary and read replicas can be of different service types and with different clusterIPs / nodePorts. Also in the case you want the primary and read replicas to be of type nodePort, you will need to set the nodePorts to different values to prevent a collision. The values that are deeper in the *primary.service* or *readReplicas.service* objects will take precedence over the top level service object.
```

2021-04-12 14:33 UTC, alemorcuq approved these changes

2021-04-12 14:49 UTC, vikram-bitnami approved these changes
Minor changes needed

2021-04-12 14:49 UTC, vikram-bitnami commented on charts/postgresql/_customize_replica_services.md.erb
> +title: Customize replica services in a replicated configuration
Not sure if "n a replicated configuration" is necessary as replica services probably don't exist otherwise?

2021-04-12 14:49 UTC, vikram-bitnami commented on charts/postgresql/_enable_tls.md.erb
> +TLS support can be enabled in the chart by specifying the *tls.* parameters while creating a release. The following parameters should be configured to properly enable the TLS support in the chart:
*tls.* -> If the idea is to use the wildcard symbol here, I think you need to add an extra *?

2021-04-12 14:49 UTC, vikram-bitnami commented on charts/postgresql/_enable_tls.md.erb
> +volumePermissions.enabled=true
Not a big deal but I guess we should be consistent in how we format code blocks? In the previous lines you used indent and here tilde symbols.

2021-04-13 08:05 UTC, vikram-bitnami commented on charts/postgresql/_configure_pod_affinity.md.erb
> +apps: postgresql, discourse
This section should be deleted as it will come from a common page.

2021-04-13 11:25 UTC, raquel-campuzano commented on charts/postgresql/_customize_replica_services.md.erb
> +title: Customize replica services in a replicated configuration
It is redundant. Good point.

2021-04-13 11:29 UTC, merged