T39962-Add install section to remaining charts
bitnami/charts-docs pull request #29
Opened 2021-04-20 10:23 UTC by raquel-campuzano

2021-04-20 10:25 UTC, carrodher approved these changes
LGTM with a minor comment

2021-04-20 10:26 UTC, carrodher commented on charts/cassandra/install.md.erb
> +        $ helm install MY-RELEASE bitnami/cassandra
We are using lowercase in the rest of cases
```suggestion
        $ helm install my-release bitnami/cassandra
```

2021-04-20 10:56 UTC, vikram-bitnami commented on charts/cassandra/install.md.erb
> +        $ helm install MY-RELEASE bitnami/cassandra
Actually, I believe it should all be uppercase, to match the partials which are already in the repository.

I don't object to using lowercase but in this case, we should then also update the existing partials and the common section to avoid inconsistency.

2021-04-20 10:58 UTC, vikram-bitnami commented on charts/wavefront/install.md.erb
> +        $ helm install my-release bitnami/wavefront --namespace wavefront \
I don't think this is the correct approach for this case. Since for this chart, we have unique installation instructions, it would be better to override the common `install` section with a chart-specific `install` section. You can create a new section with id install only for this chart, copy in the relevant steps from the common install section and add these unique steps. The specific section will override the default one when the doc system is built.

2021-04-20 10:59 UTC, vikram-bitnami commented on charts/wavefront/install.md.erb
> +        --set clusterName=<K8s-CLUSTER-NAME> \
Remove angle brackets from placeholder

Add information about placeholder replacement in steps

2021-04-20 10:59 UTC, vikram-bitnami commented on charts/wavefront/install.md.erb
> +        --set wavefront.token=<YOUR_API_TOKEN>
I assume we need to add some information at the top of this section about how to get the api token and wavefront, as it is not there currently.

2021-04-20 11:00 UTC, vikram-bitnami requested changes
See comments

2021-04-20 13:02 UTC, vikram-bitnami commented on charts/dataplatform-bp1/install.md.erb
> +        $ helm install my-release bitnami/dataplatform-bp1
Refer comment previously about consistency issue with MY-RELEASE

2021-04-27 11:21 UTC, raquel-campuzano commented on charts/wavefront/install.md.erb
> +        --set wavefront.token=<YOUR_API_TOKEN>
@vikram-bitnami I didn't find that info in the README file. The only reference we can add here is the one to the parameters section (already included). In the parameters section you can find that the value for API token is YOUR_API_TOKEN. https://github.com/bitnami/charts/tree/master/bitnami/wavefront#common-parameters

2021-04-27 12:15 UTC, carrodher approved these changes

2021-04-28 08:49 UTC, merged