T39961-Add new sections to MinIO
bitnami/charts-docs pull request #31
Opened 2021-04-20 15:30 UTC by raquel-campuzano

2021-04-23 11:06 UTC, migruiz4 requested changes
Hi @raquel-campuzano!

I found a small typo in this PR as commented below.

Apart from that, your PR looks good to me.

2021-04-23 11:06 UTC, migruiz4 commented on charts/minio/_customize_deployment.md.erb
> +Alternatively, you can use a ConfigMap or a Secret with the environment variables. To do so, use the *extraEnvVarsCM* or the *extraEnvVarsSecret* values.
Probably this is imported from here: https://github.com/bitnami/charts/blob/master/bitnami/minio/README.md#adding-extra-environment-variables

But there is a typo in the env variable `MINNIO_LOG_LEVEL`.

Also, as far as I know Minio doesn't have a variable called `MINIO_LOG_LEVEL`. It would be more appropriate to replace it with `MINIO_HTTP_TRACE` which is the Minio setting for debug logging (https://github.com/bitnami/bitnami-docker-minio#http-log-trace)

2021-04-26 09:33 UTC, migruiz4 requested changes

2021-04-26 09:33 UTC, migruiz4 commented on charts/minio/_customize_deployment.md.erb
> +        value: DEBUG
Sorry, I should've mentioned this in my previous comment.

`MINIO_HTTP_TRACE` would require a file path, so the value could be the same we use in the image [README.md](https://github.com/bitnami/bitnami-docker-minio#http-log-trace)
```suggestion
        value: /opt/bitnami/minio/log/minio.log
```

This should help both users looking how to add extraEnv variables and how to configure additional output for Minio.

2021-04-27 10:21 UTC, migruiz4 approved these changes
LGTM!

2021-04-28 09:17 UTC, merged

2021-04-28 14:06 UTC, vikram-bitnami commented on charts/minio/_configure_minio_gateway.md.erb
> +MinIO(R) can be configured as a gateway for other other storage systems. This chart currently supports to setup MinIO(R) as a gateway for the storage systems below:
other other -> typo

2021-04-28 14:06 UTC, vikram-bitnami commented on charts/minio/_configure_use_sidecars.md.erb
> +title: Configure and use sidecar containers
This file is not needed as it is now a common section which will appear automatically. It should be deleted unless it needs to be unique for some reason.