T39353 Created common sections
bitnami/charts-docs pull request #36
Opened 2021-05-07 10:23 UTC by vikram-bitnami

2021-05-07 10:31 UTC, vikram-bitnami commented on _scale_deployment.md.erb
> +apps: none
There seem to be multiple options in our charts for these parameters, both for the password variable and the replica variable. It was therefore difficult to write this as a common section which appears within each  chart documentation. Therefore I made this an FAQ entry (allows it to be more generic) and within each chart we have a common section which asks users to check this FAQ.

2021-05-07 10:31 UTC, vikram-bitnami commented on charts/discourse/_scale_deployment.md.erb
>  apps: discourse
This content seems unique for Discourse as it does not match the sections seen in other charts. However I'm not sure if it is out of date. Please check it once.

2021-05-07 10:31 UTC, vikram-bitnami commented on charts/etcd/_enable_metrics.md.erb
>  Metrics can be scraped from within the cluster using something similar to the example [Prometheus scrape configuration](https://github.com/prometheus/prometheus/blob/master/documentation/examples/pro
Custom metrics section for etcd because of the metrics.podMonitor parameter which is not part of the common section.

2021-05-07 10:31 UTC, vikram-bitnami commented on charts/etcd/_scale_deployment.md.erb
> +* Upgrade the StatefulSet by providing the total number of etcd members required in the etcd cluster as a parameter to the *helm upgrade* command. For instance, to remove two members, use the command
Custom section for etcd as it seems to have extra steps different from the common section.

2021-05-07 10:31 UTC, vikram-bitnami commented on charts/kafka/_enable_metrics.md.erb
>  highlight: 20
Custom metrics section for Kafka as it has two exporters. Please reconfirm.

2021-05-07 10:31 UTC, vikram-bitnami commented on charts/rabbitmq/_scale_deployment.md.erb
> +id: scale_deployment
Custom rabbitmq section as it is different from the common scale-deployment content. Please reconfirm.

2021-05-07 10:31 UTC, vikram-bitnami commented on charts/redis-cluster/_scale_deployment.md.erb
> +id: scale_deployment
Custom section for this chart as it is different from the common sections. Please reconfirm.

2021-05-07 10:31 UTC, vikram-bitnami commented on common/_deploy_extra_resources.md.erb
> +apps: airflow, apache, cassandra, consul, dokuwiki, drupal, etcd, fluentd, ghost, grafana, grafana-operator, harbor, influxdb, jasperreports, jenkins, joomla, jupyterhub, kafka, keycloak, kiam, kong,
Please recheck app list for which this section applies. I based it on a parameter search in the chart repo.

2021-05-07 10:31 UTC, vikram-bitnami commented on common/_enable_metrics.md.erb
> +apps: airflow, apache, cassandra, consul, dataplatform-bp1, dataplatform-bp2, dokuwiki, drupal, elasticsearch, external-dns, fluentd, grafana, influxdb, jenkins, joomla, keycloak, kiam, kibana, kong,
Please recheck app list for which this section applies. I based it on a parameter search in the chart repo.

2021-05-07 10:31 UTC, vikram-bitnami commented on common/_scale_deployment.md.erb
> +apps: elasticsearch, external-dns, harbor, metrics-server, mongodb-sharded, redmine, wavefront, airflow, apache, aspnet-core, cassandra, consul, contour, dataplatform-bp1, drupal, ejbca, fluentd, gho
Please recheck app list for which this section applies. I based it on a parameter search in the chart repo. Note there are some custom versions of this section for some charts eg. etcd rabbitmq as their READMEs seem to have extra chart-specific info, so those are not part of this list.

2021-05-07 10:31 UTC, vikram-bitnami commented on common/_scale_deployment.md.erb
> +<% elsif %w(dataplatform-bp2 kube-state-metrics magento).include? current.app  %>
Please recheck this, i saw these charts contain both replicas and replicaCount parameters, hence extra conditional in doc.

2021-05-07 10:32 UTC, vikram-bitnami commented
This PR covers all the common section changes discussed with @javsalgar in the Configuration #2 tab of the working document, EXCEPT the changes for the TLS section which are under discussion. TLS changes will be added once pending questions are clarified.

2021-05-10 09:50 UTC, Mauraza commented on common/_enable_metrics.md.erb
> +apps: airflow, apache, cassandra, consul, dataplatform-bp1, dataplatform-bp2, dokuwiki, drupal, elasticsearch, external-dns, fluentd, grafana, influxdb, jenkins, joomla, keycloak, kiam, kibana, kong,
`dataplatform-bpX`, there a chart of charts, I think you don't have to add, @miguelaeh, could you confirm this?

2021-05-10 09:50 UTC, Mauraza commented on common/_scale_deployment.md.erb
> +apps: elasticsearch, external-dns, harbor, metrics-server, mongodb-sharded, redmine, wavefront, airflow, apache, aspnet-core, cassandra, consul, contour, dataplatform-bp1, drupal, ejbca, fluentd, gho
the same here about `dataplatform-bpX`

2021-05-17 09:54 UTC, vikram-bitnami commented
@javsalgar @juan131 could you please review this?

2021-05-18 13:13 UTC, juan131 requested changes

2021-05-18 13:13 UTC, juan131 commented on _scale_deployment.md.erb
> +* Use the *kubectl scale* command to scale the StatefulSet, if available.
`To scale a deployment (...) command to scale the statefulset`

⚠️ deployment != statefulset

They're similar concepts, but not the same. We should be consistent. Suggestion: 

```suggestion
To scale a deployment or statefulset, two options are available:

* Use the *kubectl scale* command to scale the deployment or statefulset, if available.
```

This applies to whole file

2021-05-18 13:13 UTC, juan131 commented on charts/discourse/_scale_deployment.md.erb
>  apps: discourse
Indeed it applies to every web app. I mean, our web apps can't be installed with more than one replica. To scale them, you need to:
- Install with one replica
- Wait for the 1st boot (1st initialization) to be completed
- Upgrade to N replicas
Also, to scale our web apps you need to use ReadWriteMany volumes if persistence is enabled.

2021-05-18 13:13 UTC, juan131 commented on charts/etcd/_enable_metrics.md.erb
> +To start the sidecar Prometheus exporter, set the *\*.metrics.enabled* parameter to *true* when deploying the chart.
This is wrong, this chart doesn't use a sidecar. **etcd** has the ability to expose the metrics without needing a sidecar to adapt metrics to Prometheus format.
This is something common in Cloud Native apps such as etcd or NATS

2021-05-18 13:13 UTC, juan131 commented on charts/etcd/_scale_deployment.md.erb
> +* Upgrade the StatefulSet by providing the total number of etcd members required in the etcd cluster as a parameter to the *helm upgrade* command. For instance, to remove two members, use the command
I confirm it should be different. Also, we're mixing here again deployment and statefulset concepts

2021-05-18 13:13 UTC, juan131 commented on common/_enable_metrics.md.erb
> +          prometheus.io/port: ""9000""
Why did you use MinIO as example?

2021-05-18 13:13 UTC, juan131 commented on common/_enable_metrics.md.erb
> +To start the sidecar Prometheus exporter, set the *metrics.enabled* parameter to *true* when deploying the chart. Refer to the chart parameters for the default port number.
MinIO, Grafana, and other apps in that list don't use sidecars. They expose the metrics by themselves.

2021-05-18 13:13 UTC, juan131 commented on common/_enable_metrics.md.erb
> +* Creating a PodMonitor entry (when the Prometheus Operator is available in the cluster)
```suggestion
* Creating a ServiceMonitor or PodMonitor entry (when the Prometheus Operator is available in the cluster)
```

2021-05-18 13:13 UTC, juan131 commented on common/_enable_tls.md.erb
> +        tls.certCAFilename="ca.pem"
What cart did you use as reference? These parameter are available in very few of the charts.

2021-05-18 14:45 UTC, vikram-bitnami commented on _scale_deployment.md.erb
> +    $ kubectl scale --replicas=4 statefulset/my-release-etcd
Could you please suggest a more generic example or some generic placeholders we should add in the command to cover those cases?

2021-05-18 14:45 UTC, vikram-bitnami commented on _scale_deployment.md.erb
> +* Use the *kubectl scale* command to scale the StatefulSet, if available.
Made changes, could you please review again?

2021-05-18 14:45 UTC, vikram-bitnami commented on charts/discourse/_scale_deployment.md.erb
>  apps: discourse
I am leaving the discourse-specific section as is, since the examples/code are very specific to discourse. I added the point about RWX volumes to the common FAQ. Let me know if you can suggest anything further.

2021-05-18 14:45 UTC, vikram-bitnami commented on charts/etcd/_enable_metrics.md.erb
> +To start the sidecar Prometheus exporter, set the *\*.metrics.enabled* parameter to *true* when deploying the chart.
Changed

2021-05-18 14:45 UTC, vikram-bitnami commented on common/_enable_metrics.md.erb
> +To start the sidecar Prometheus exporter, set the *metrics.enabled* parameter to *true* when deploying the chart. Refer to the chart parameters for the default port number.
Could you please let me know which apps (refer metadata for list) use sidecars and which don't? I will create two versions of this section accordingly.

2021-05-18 14:45 UTC, vikram-bitnami commented on common/_enable_metrics.md.erb
> +          prometheus.io/port: ""9000""
Fixed

2021-05-18 14:45 UTC, vikram-bitnami commented on common/_enable_tls.md.erb
> +        tls.certCAFilename="ca.pem"
As per discussion with @javsalgar in the Google Doc. See the doc link in https://phabricator.nami.run/T39353#945987. If you can let me know which apps it applies to, I can update the metadata

2021-05-20 08:46 UTC, juan131 requested changes

2021-05-20 08:46 UTC, juan131 commented on common/_enable_metrics.md.erb
> +To start the sidecar Prometheus exporter, set the *metrics.enabled* parameter to *true* when deploying the chart. Refer to the chart parameters for the default port number.
This is the list of assets that expose the metrics by themselves (without needing a sidecar):

InfluxDB, Zookeeper, Spark, Thanos, etcd, Keycloak, Kong, Grafana, RabbitMQ, Cert manager, Fluentd, ExternalDNS, Spring Cloud Data Flow and NGINX Ingress Controller

2021-05-20 08:46 UTC, juan131 commented on common/_enable_tls.md.erb
> +        tls.certCAFilename="ca.pem"
Only these assets have a `tls.*` section: postgresql, fluentd, redis, redis-cluster, minio, mongodb, solr, mariadb-galera
That said, the parameters may differ from one chart to another

2021-05-21 11:12 UTC, vikram-bitnami commented on common/_enable_metrics.md.erb
> +To start the sidecar Prometheus exporter, set the *metrics.enabled* parameter to *true* when deploying the chart. Refer to the chart parameters for the default port number.
Fixed

2021-05-21 11:14 UTC, vikram-bitnami commented
Please recheck @javsalgar @juan131 - thanks

2021-05-26 13:22 UTC, juan131 requested changes
Just a minor comment regarding the TLS section.

---

For the future: Please avoid this kind of PRs affecting so many files @vikram-bitnami . I get lost every-time I need to review so many changes. Instead, send several PRs with fewer changes.

2021-05-26 13:22 UTC, juan131 commented on _scale_deployment.md.erb
> +* Upgrade the deployment or StatefulSet configuring a different number of nodes.
Just curious: Why do you se `deployment` (lowercase) and `Statefulset` (camelCase)?

2021-05-26 13:22 UTC, juan131 commented on common/_enable_tls.md.erb
> +apps: postgresql, fluentd, redis, redis-cluster, minio, solr, mariadb-galera
As I said on a previous comment the parameters the parameters may differ from one chart to another. For instance, I can't find the "tls.certificatesSecret" parameter in Fluentd or MinIO.
Please double-check the parameters mentioned on this guide exist on every chart in this list.

2021-05-26 15:00 UTC, vikram-bitnami commented on _scale_deployment.md.erb
> +* Upgrade the deployment or StatefulSet configuring a different number of nodes.
This is actually an inconsistency in our docs and deployment needs to be fixed globally (it should be capitalized as you say). We will be doing this separately at a later point across  all docs.

2021-05-26 15:04 UTC, vikram-bitnami commented
@juan131 updated and replied to your comments

2021-05-26 15:04 UTC, vikram-bitnami commented on common/_enable_tls.md.erb
> +apps: postgresql, fluentd, redis, redis-cluster, minio, solr, mariadb-galera
Modified

2021-05-27 06:38 UTC, juan131 commented on _scale_deployment.md.erb
> +* Upgrade the deployment or StatefulSet configuring a different number of nodes.
Fair enough

2021-05-27 06:39 UTC, juan131 approved these changes
LGTM

2021-05-27 08:02 UTC, miguelaeh commented on charts/redis-cluster/_scale_deployment.md.erb
> +id: scale_deployment
Yes, this is different from other charts, the instructions below seems incorrect to upgrade the cluster

2021-05-27 08:02 UTC, miguelaeh commented on common/_enable_metrics.md.erb
> +apps: airflow, apache, cassandra, consul, dataplatform-bp1, dataplatform-bp2, dokuwiki, drupal, elasticsearch, external-dns, fluentd, grafana, influxdb, jenkins, joomla, keycloak, kiam, kibana, kong,
in `dataplatform-bpX` charts the metrics can be enabled using the subchart parameters

2021-05-27 10:26 UTC, vikram-bitnami commented on charts/redis-cluster/_scale_deployment.md.erb
> +id: scale_deployment
Can you please let me know what are the correct instructions for this chart?

2021-05-28 08:29 UTC, miguelaeh commented on charts/redis-cluster/_scale_deployment.md.erb
> +id: scale_deployment
Hi @vikram-bitnami , they are documented [here](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#adding-a-new-node-to-the-cluster])

2021-05-28 15:05 UTC, vikram-bitnami commented
Please check again @miguelaeh

2021-05-31 08:42 UTC, miguelaeh approved these changes
LGTM!

2021-05-31 09:56 UTC, merged