Include Cert Manager doc examples
bitnami/charts-docs pull request #37
Opened 2021-05-18 09:56 UTC by alvneiayu

Include ACME and self signed example. Moreover, include ingress section.

2021-05-18 12:57 UTC, juan131 requested changes
Thanks for the docs! Please check my comments

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_create_or_configure_ingress.md.erb
> +Just enable the key ingress.certManager and include inside the ingress annotations:
```suggestion
- Deploy another Helm chart with support to expose the application through an Ingress controller. For instance, using the [Bitnami Helm Chart for WordPress](https://github.com/bitnami/charts/tree/master/bitnami/wordpress) you can expose WordPress as explained in [this section](https://docs.bitnami.com/kubernetes/apps/wordpress/configuration/configure-ingress/). To enable the integration with CertManager, set the *ingress.certManager* parameter to *true* and add the annotations below to the *ingress.annotations* parameter:
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_create_or_configure_ingress.md.erb
> +kubernetes.io/ingress.class: nginx
You're assuming the user is using NGINX Ingress Controller, but any other Ingress Controller could be use (e.g. Contour+Envoy)

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_create_or_configure_ingress.md.erb
> +- Create your own ingress, here you can find an example:
```suggestion
- Create your own ingress resource as shown in the example below:
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_create_or_configure_ingress.md.erb
> +    kubernetes.io/ingress.class: "nginx"
Again, you're assuming that NGINX Ingress Controller is being used. At least, you should state it

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +title: Generate certificate signing with ACME
```suggestion
id: generate_acme_certificates
title: Generate TLS certificates using ACME Issuer
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +Cert Manager allow to sign certificates with different ways. One of this ways is to use ACME (Automated Certificate Management Environment).
```suggestion
Cert Manager has support to issue certificates using different Issuers. For instance, you can use a public ACME (Automated Certificate Management Environment) server to issue the certificates.

> Note: find the list of available Issuers in the [Cert Manager official documentation](https://cert-manager.io/docs/configuration/#supported-issuer-types).
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +in your Issuer is yours. Cert Manager have two different challenges to verify that you are the proprietary of your domain HTTP01 or DNS01, more information [here](https://cert-manager.io/docs/concept
```suggestion
To configure Cert Manager you need to create an Issuer object, which structure defers depending on the Issuer type. To use ACME, we should include the information of a single account registered in the ACME Certificate Authority server.

Once Cert Manager is configured to use ACME, it will verify that you are the owner of the domains you're trying to generate certificates for. This can be done in two ways: using HTTP01 or DNS01 challenges.

> Note: learn more about the process to solve challenges in the [official documentation](https://cert-manager.io/docs/configuration/acme/#solving-challenges).
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +To create a ACME issuer to generate the certificate using let's encrypt, we need to declare an Issuer:
```suggestion
To create a ACME issuer to generate the certificate using Let's Encrypt, declare an Issuer:
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +    email: bn_certmanager@bitnami.com
```suggestion
    email: user@example.com
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +To use the ClusterIssuers inside our ingress, take a look the section "Create or configure an ingress using Cert Manager").
```suggestion
Now, you can use the ClusterIssuer to generate certificates for the applications you want to expose in your K8s cluster. [Learn how to secure your Ingress resources](<%= platform_path %>/infrastructure/cert-manager/configuration/secure-ingress-resources).
```

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificate.md.erb
> +Wait until the Ingress is ready (this example follows the own ingress configuration). Then, Cert Manager will begin to verify using HTTP01 that you are the proprietary of your own domain. During this
> this example follows the own ingress configuration.

I don't understand this

2021-05-18 12:57 UTC, juan131 commented on charts/cert-manager/_generate_self_signed_certificate.md.erb
> +Including those elements, Cert Manager will create a secret including the certificates generated. Here you can find one example:
Many of the suggestions I gave you for ACME apply here

2021-05-20 08:57 UTC, juan131 requested changes

2021-05-20 08:57 UTC, juan131 commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +in your Issuer is yours. Cert Manager have two different challenges to verify that you are the proprietary of your domain HTTP01 or DNS01, more information [here](https://cert-manager.io/docs/concept
Isn't this the same info that you have in line 18?

2021-05-20 08:57 UTC, juan131 commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +Once the issuer is already configured. Cert Manager using this issuer will create a secret that the content is a TLS certificate. To create this TLS certificate, Cert Manager must detect that your de
```suggestion
Once you configure an Issuer for Cert Manager (refer to one these two guides to so: [Using a Self-Signed Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-self-signed-certificates) or [Using a ACME Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-acme-certificates)), Cert Manager will make use of this Issuer to create a TLS secret containing the certificates. To create this secret, Cert Manager must previously detect that your application is already exposed. One way to do it is using an Ingress Resource to expose the application including the corresponding annotations for Cert Manager.
```

2021-05-20 08:57 UTC, juan131 commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +You have two different options to expose your application including Cert Manager:
```suggestion
You have two different options to expose your application through an Ingress Controller using Cert Manager to manage the TLS certificates:
```

2021-05-26 10:30 UTC, vikram-bitnami requested changes

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +Once you configure an Issuer for Cert Manager (refer to one these two guides to so: [Using a Self-Signed Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-self-signed-ce
Once you configure an Issuer for Cert Manager (either [a Self-Signed Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-self-signed-certificates) or [an ACME Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-acme-certificates)),

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +Once you configure an Issuer for Cert Manager (refer to one these two guides to so: [Using a Self-Signed Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-self-signed-ce
One way to do this is with an Ingress Resource which exposes the application and includes the corresponding annotations for Cert Manager.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +- Create your own ingress resource as shown in the example below:
Ingress

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +    - bitnami.com
Use DOMAIN instead and explain above "Replace the DOMAIN placeholder with the correct domain name"

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +  name: bitnami-ingress-test
Avoid using bitnami in these examples so that this can be reused in non-bitnami-specific docs as well

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +You have two different options to expose your application through an Ingress Controller using Cert Manager to manage the TLS certificates:
There are two options...

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +- Deploy another Helm chart with support to expose the application through an Ingress controller. For instance, using the [Bitnami Helm Chart for WordPress](https://github.com/bitnami/charts/tree/mas
Deploy another Helm chart which supports exposing the application through an Ingress controller. For instance, use the [Bitnami Helm Chart for WordPress](https://github.com/bitnami/charts/tree/master/bitnami/wordpress) and [configure Ingress for WordPress](<%= platform_path %>/apps/wordpress/configuration/configure-ingress/).

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +~~~
Shouldn't these blocks be indented as they are part of the list? Please check if it is rendered properly.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +Cert Manager has support to issue certificates using different Issuers. For instance, you can use a public ACME (Automated Certificate Management Environment) server to issue the certificates.
Cert Manager supports issuing certificates through different Issuers.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +> Note: find the list of available Issuers in the [Cert Manager official documentation](https://cert-manager.io/docs/configuration/#supported-issuer-types).
> NOTE: Find ...

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +To configure Cert Manager you need to create an Issuer object, which structure defers depending on the Issuer type. To use ACME, we should include the information of a single account registered in th
To configure Cert Manager, create an Issuer object. The structure of this object differs depending on the Issuer type. For ACME, it is necessary to  include the information for a single account registered in the ACME Certificate Authority server.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +title: Generate TLS certificates using ACME Issuer
Issuers

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +Once Cert Manager is configured to use ACME, it will verify that you are the owner of the domains you're trying to generate certificates for. Cert Manager have two different challenges to verify that
domains for which certificates are being requested.

Cert Manager uses two different challenges to verify that you are the owner of your domain: HTTP01 or DNS01. [Learn more about ACME challenges](https://cert-manager.io/docs/concepts/acme-orders-challenges/#challenge-scheduling).

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +> Note: learn more about the process to solve challenges in the [official documentation](https://cert-manager.io/docs/configuration/acme/#solving-challenges).
> NOTE: Learn

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +To create a ACME issuer to generate the certificate using Let's Encrypt, declare an Issuer:
To create a ACME issuer for use with Let's Encrypt, declare an Issuer as shown below:

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +- Issuer
This line can be deleted, not clear why we are starting a new list here.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +    email: user@example.com
Use EMAIL-ADDRESS placeholder and explain it in the preceding sentence. See example in comments further down.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +Now, you can use the ClusterIssuer to generate certificates for the applications you want to expose in your K8s cluster. [Learn how to secure your Ingress resources](<%= platform_path %>/infrastructu
Next, use the ClusterIssuer to generate certificates for the applications in your Kubernetes cluster.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +Now, you can use the ClusterIssuer to generate certificates for the applications you want to expose in your K8s cluster. [Learn how to secure your Ingress resources](<%= platform_path %>/infrastructu
How do you "use the ClusterIssuer to generate certificates for the applications"? Can you add an example of the command?

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +After your Ingress resource is ready. Cert Manager begins to verify using HTTP01/DNS01 challenges that you are the proprietary of your own domain. During this verification, you can log the controller
After the Ingress resource is ready, Cert Manager verifies the domain using HTTP01/DNS01 challenges. During this verification process, the controller log can be used to check the status, as shown below:

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +You will see that the ready status is False. This status will change to True when the HTTP01 verification is succesfully and over.
The status remains *False* whilst verification is in progress. This status will change to *True* when the HTTP01 verification is completed successfully.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +$ k get secrets
What is the purpose of this command?

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +title: Generate TLS certificates using Self Signed Issuer
Issuers

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +Cert Manager has support to issue certificates using different Issuers. For instance, you can use a Self Signed to issue the certificates.
Cert Manager supports issuing certificates through different Issuers.

For instance, you can use a Self Signed Issuer to issue the certificates.

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +The SelfSigned issuer doesn’t represent a certificate authority as such, but instead denotes that certificates will “sign themselves” using a given private key.
Self Signed

It looks like this sentence uses "smart quotes", could you please check and replace with regular quotes?

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +> Note: find the list of available Issuers in the [Cert Manager official documentation](https://cert-manager.io/docs/configuration/#supported-issuer-types).
> NOTE: Find

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +To configure Cert Manager you need to create an Issuer object, which structure defers depending on the Issuer type. Self Signed issuer are really easy to configure.
Update sentence as per prev section

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +Now, you can use the ClusterIssuer to generate certificates for the applications you want to expose in your K8s cluster. [Learn how to secure your Ingress resources](<%= platform_path %>/infrastructu
Update sentence as per prev section

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +To create a self signed issuer to generate a self signed certificate, declare an Issuer, a ClusterIssuer and a Certificate:
, as shown below:

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +- ClusterIssuer
Normally would these definitions be in separate files or could they also be in a single file? If single file is supported, could we concatenate all these code blocks into a single one and remove the list structure?

2021-05-26 10:30 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +With our application already exposed using an Ingress resource. Cert Manager will create a secret which the content is the TLS certificate generated.
With the application already exposed using an Ingress resource, Cert Manager will create a secret whose  content is the TLS certificate generated. This can be checked as shown below:

2021-06-06 11:23 UTC, alvneiayu commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +~~~
I think so. I changed it and I am verifying that everything is rendered as expected.

2021-06-06 11:23 UTC, alvneiayu commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +Now, you can use the ClusterIssuer to generate certificates for the applications you want to expose in your K8s cluster. [Learn how to secure your Ingress resources](<%= platform_path %>/infrastructu
The way to include it is using an ingress. The user should take a look the url defined after this sentences ("Learn how to secure your Ingress resource")

2021-06-06 11:23 UTC, alvneiayu commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +$ k get secrets
To show the secret created by the cert manager. This secret contains the certificates generated by cert manager. Just to show the way to verify that everything is working properly (or generated properly).

2021-06-06 11:23 UTC, alvneiayu commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +- ClusterIssuer
We can concatenate them as a single one block, so I modified it.

2021-06-07 08:01 UTC, alvneiayu commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +~~~
Tested and now it is rendering properly

2021-06-09 09:26 UTC, juan131 approved these changes
LGTM

2021-06-16 06:12 UTC, migruiz4 commented
Hi @alvneiayu,

Your PR looks good to me, but I noticed that your examples are using `k` as alias for `kubectl`.
Although `k` is widely used, I'd recommend using the full command instead of the alias as not every user may have the alias configured and could find the examples confusing.

2021-06-16 06:52 UTC, alvneiayu commented
Done, thanks @migruiz4. Good catch

2021-06-18 15:24 UTC, vikram-bitnami approved these changes
This looks fine, although I have some minor changes. Please make the changes and go ahead and merge (or ping me for the merge).

2021-06-18 15:24 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +The status remains False whilst verification is in progress. This status will change to True when the HTTP01 verification is completed successfully.
*False*
*True*

2021-06-18 15:24 UTC, vikram-bitnami commented on charts/cert-manager/_generate_self_signed_certificates.md.erb
> +After the Ingress resource is ready, Cert Manager will create a secret whose content is the TLS certificate generated. This can be checked as shown below:
After the Ingress resource is ready, Cert Manager will create a secret. This secret contains the generated TLS certificate.

2021-06-18 15:24 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +Once you configure an Issuer for Cert Manager (either [a Self-Signed Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-self-signed-certificates) or [an ACME Issuer](<%=
To create this secret, Cert Manager must previously detect that your application is already exposed.

I don't understand this sentence, could you clarify what you mean? Maybe it is clearer to say `Cert Manager can only create this secret if the application is already exposed.`?

2021-06-18 15:24 UTC, vikram-bitnami commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +- Deploy another Helm chart which supports exposing the application through an Ingress controller. For instance, use the [Bitnami Helm Chart for WordPress](https://github.com/bitnami/charts/tree/mast
Minor but we use asterisks for lists

2021-06-18 15:24 UTC, vikram-bitnami commented on charts/cert-manager/_generate_acme_certificates.md.erb
> +The status remains False whilst verification is in progress. This status will change to True when the HTTP01 verification is completed successfully.
@alvneiayu please check my review comments

2021-06-22 09:55 UTC, alvneiayu commented on charts/cert-manager/_secure_ingress_resources.md.erb
> +Once you configure an Issuer for Cert Manager (either [a Self-Signed Issuer](<%= platform_path %>/infrastructure/cert-manager/configuration/generate-self-signed-certificates) or [an ACME Issuer](<%=
I like your proposal, I changed it to use yours. As you said, It is clearer.

2021-06-22 10:13 UTC, merged