T40424 Changes to reuse content for TAC platform documentation
bitnami/charts-docs pull request #43
Opened 2021-06-08 08:12 UTC by vikram-bitnami

2021-06-08 08:13 UTC, vikram-bitnami commented
The main changes here are:
- using variable names for the repository and the catalog in all content
- updating the metadata to include the new platform
- customized installation steps for each platform

It is a large diff because of the global replacement for variables.

2021-06-08 09:55 UTC, rafariossaa commented
Hi @vikram-bitnami ,
  I am not very sure about the change:

```console
$ helm install MY-RELEASE  ....
```
  My concern is that users usually copy and paste from instructions and if they use capitals for the deployment name they are going to have errors like this:

```console
$ helm install MY-RELEASE bitnami/mysql
Error: create: failed to create: Secret "sh.helm.release.v1.MY-RELEASE.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.MY-RELEASE.v1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

2021-06-08 10:55 UTC, vikram-bitnami commented
> Hi @vikram-bitnami ,
> I am not very sure about the change:
> 
> ```
> $ helm install MY-RELEASE  ....
> ```
> 
> My concern is that users usually copy and paste from instructions and if they use capitals for the deployment name they are going to have errors like this:
> 
> ```
> $ helm install MY-RELEASE bitnami/mysql
> Error: create: failed to create: Secret "sh.helm.release.v1.MY-RELEASE.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.MY-RELEASE.v1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
> ```

Thanks for pointing this out. I have made a separate task for this (to make it easier for review as there are many files this change will touch) and pinged you in it. For the moment, I have also updated this diff to include a note on the naming rules for release names.

2021-06-09 09:32 UTC, juan131 requested changes
A minor comment

2021-06-09 09:32 UTC, juan131 commented on charts/wavefront/_install_tac.md.erb
> +   The [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/wavefront#parameters) section lists the parameters that can be configured during installation.
Cannot this be merged with `common/_install_tac.md.erb`?

2021-06-09 09:32 UTC, juan131 commented on charts/wavefront/_install_kubernetes.md.erb
> +   The [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/wavefront#parameters) section lists the parameters that can be configured during installation.
Cannot this be merged with `common/_install_kubernetes.md.erb`?

2021-06-09 09:36 UTC, vikram-bitnami commented on charts/wavefront/_install_tac.md.erb
> +   The [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/wavefront#parameters) section lists the parameters that can be configured during installation.
I created a separate document because there are additional steps needed for this app ie. in this case we are creating an additional namespace and also passing specific additional parameters to the install command. IMO this is a good case for using the BDS feature of overriding a default/generic install section with a custom app-specific section.

2021-06-09 09:38 UTC, vikram-bitnami commented on charts/wavefront/_install_tac.md.erb
> +   The [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/wavefront#parameters) section lists the parameters that can be configured during installation.
I would consider the case for merging with the common section stronger if there was only a minor difference, such as an extra note or a few extra sentences. In this case the delta seemed large enough to justify a separate file. However if you still prefer it all in one common file, that is technically feasible and can be done

2021-06-18 07:07 UTC, juan131 commented on charts/wavefront/_install_tac.md.erb
> +   The [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/wavefront#parameters) section lists the parameters that can be configured during installation.
👍

2021-06-18 07:07 UTC, juan131 commented on charts/wavefront/_install_kubernetes.md.erb
> +   The [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/wavefront#parameters) section lists the parameters that can be configured during installation.
👍

2021-06-18 07:07 UTC, juan131 approved these changes
LGTM

2021-06-21 13:56 UTC, merged