redis: Add docs for setting up custom scripts in the metrics sidecar
bitnami/charts-docs pull request #56
Opened 2021-07-20 19:17 UTC by 0xDEC0DE

Depends on: https://github.com/bitnami/charts/pull/6806

2021-07-21 10:20 UTC, alemorcuq commented
Thanks for the PR. Let's block this until https://github.com/bitnami/charts/pull/6806 is solved.

2021-07-22 09:09 UTC, vikram-bitnami requested changes

2021-07-22 09:09 UTC, vikram-bitnami commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +A custom Lua script can be added to the `redis-exporter` sidecar by way of the `metrics.extraArgs.script` parameter.  The pathname of the script *MUST* exist on the container, or the `redis_exporter`
A custom Lua script can be added to the *redis-exporter* sidecar by way of the *metrics.extraArgs.script* parameter. The script can be provided to the sidecar containers via the *extraVolumes* and *extraVolumeMounts* parameters, as shown below:

> NOTE: The pathname of the script must exist on the container, or the *redis_exporter* process (and therefore the whole pod) will refuse to start.

2021-07-22 09:09 UTC, vikram-bitnami commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +Then deploy the script into the correct location via `extraDeploy`:
Use italics (*) instead of backticks for these docs.

2021-07-22 09:09 UTC, vikram-bitnami commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +In this example, the custom script would appear in the sidecar container as `/mnt/my-redis-deploy/my_custom_metrics.lua`, and the `redis-exporter` command
As above

2021-07-22 09:09 UTC, vikram-bitnami commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +              -- a super-clever Lua script goes here
-- LUA SCRIPT CODE HERE

2021-07-22 09:39 UTC, alemorcuq requested changes
Blocked. Waiting for https://github.com/bitnami/charts/pull/6806

2021-07-22 20:31 UTC, 0xDEC0DE reviewed
Pushed a new version to align with the changes in https://github.com/bitnami/charts/pull/6806

2021-07-26 07:43 UTC, alemorcuq requested changes
Waiting for https://github.com/bitnami/charts/pull/6806

2021-08-31 22:24 UTC, 0xDEC0DE commented
https://github.com/bitnami/charts/pull/6806 is merged, this can be unblocked.

2021-09-02 11:33 UTC, alemorcuq requested changes

2021-09-02 11:33 UTC, alemorcuq commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +    my-redis-deploy:
I would remove this `my-redis-deploy` line and just leave the actual values that have to be set.

2021-09-02 11:33 UTC, alemorcuq commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +    my-redis-deploy:
Same as above

2021-09-02 11:33 UTC, alemorcuq commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +          script: "/mnt/my-redis-deploy/my_custom_metrics.lua"
You are using are using a dynamic path in the `extraVolumeMounts` definition but hardcoding it to `my-redis-deploy` here. Please, choose one or the other.

2021-09-02 11:33 UTC, alemorcuq commented
Now that this is unblocked, can you review it again, @vikram-bitnami ?

2021-09-02 17:48 UTC, 0xDEC0DE commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +    my-redis-deploy:
Done.

2021-09-02 17:48 UTC, 0xDEC0DE commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +    my-redis-deploy:
Done.

2021-09-02 17:48 UTC, 0xDEC0DE commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +          script: "/mnt/my-redis-deploy/my_custom_metrics.lua"
Done.

2021-09-03 09:37 UTC, vikram-bitnami approved these changes

2021-09-03 09:41 UTC, alemorcuq requested changes

2021-09-03 09:41 UTC, alemorcuq commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +        script: '{{`{{ printf "/mnt/%s/my_custom_metrics.lua" (include "common.names.name" .) }}`}}'
I think this is a typo. Should it be like this instead?

```suggestion
        script: '{{ printf "/mnt/%s/my_custom_metrics.lua" (include "common.names.name" .) }}'
```

2021-09-03 09:41 UTC, alemorcuq commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +          name: '{{`{{ printf "%s-metrics-script" (include "common.names.fullname" .) }}`}}'
Same as above.

2021-09-08 00:10 UTC, 0xDEC0DE commented on charts/redis/_deploy_custom_metrics_script.md.erb
> +        script: '{{`{{ printf "/mnt/%s/my_custom_metrics.lua" (include "common.names.name" .) }}`}}'
Not strictly a typo, but I'm one of those dirty `helmfile` users, and we have to do weird things to get template directives to work sometimes.  I forgot to strip them out for this.

Will fix.

2021-09-08 07:51 UTC, alemorcuq approved these changes
Thanks for the contribution!

2021-09-08 07:51 UTC, merged