Transferred and updated WordPress and MariaDB sections
bitnami/charts-docs pull request #7
Opened 2021-02-05 13:31 UTC by vikram-bitnami

2021-02-08 14:35 UTC, juan131 requested changes
Thanks for the PR @vikram-bitnami ! Please check my comments.
You're facing an issue constantly related to not finish your files with a new line. You can fix this by configuring your editor properly. If you use VSCode, visit this issue in SO: https://stackoverflow.com/questions/44704968/visual-studio-code-insert-new-line-at-the-end-of-files

2021-02-08 14:35 UTC, juan131 commented on charts/mariadb/_configure_use_init_containers.md.erb
> +If additional containers are needed in the same pod as MariaDB, they can be defined using the *initContainers* parameter. Here is an example:
You're using the same sentence both on "init containers" and "sidecar" containers, so it's confusing. I'd state that difference:
```suggestion
Additional init containers can be added to MariaDB pods using the *initContainers* parameter. Here is an example:
```

2021-02-08 14:35 UTC, juan131 commented on charts/mariadb/_customize_new_instance.md.erb
> +        fi
```suggestion
~~~
initdbScripts:
  my_init_script.sh: |
    #!/bin/sh
    if [[ $(hostname) == *primary* ]]; then
        echo "Primary node"
        mysql -P 3306 -uroot -prandompassword -e "create database new_database";
    else
        echo "No primary node"
    fi
~~~
```

2021-02-08 14:35 UTC, juan131 commented on charts/mariadb/_understand_chart_persistence.md.erb
> +Typically, this occurs because the image runs as a non-root user and in some Kubernetes clusters, non-root users do not have write privileges.In such cases, it is necessary to adjust the ownership of
```suggestion
Typically, this occurs because the image runs as a non-root user and in some Kubernetes clusters, non-root users do not have write privileges. In such cases, it is necessary to adjust the ownership of the persistent volume so that the container can write data into it. There are two approaches to achieve this:
```

2021-02-08 14:35 UTC, juan131 commented on charts/wordpress/_configure_use_ingress.md.erb
> +However, it is also possible to have more than one host. To facilitate this, the *ingress.extraHosts* object can be set, with the host names specified as an array. The *ingress.extraTLS* parameter ca
IMHO, it's weird to talk about the `ingress.extraTLS` parameter, without previously talking about the `ingress.tls` parameter (that only affects to the hostname defined with `ingress.hostname` property).

2021-02-08 14:35 UTC, juan131 commented on charts/wordpress/_configure_use_sidecars.md.erb
> +~~~
Fix the "no newline at end of file" warning.

2021-02-08 14:35 UTC, juan131 commented on charts/mariadb/_add_nodes.md.erb
> +~~~
Fix the "no newline at end of file" warning.

2021-02-08 14:35 UTC, juan131 commented on charts/wordpress/_understand_chart_persistence.md.erb
> +PersistenceVolumeClaims (PVCs) are used to keep the data across deployments. This is known to work in GCE, AWS, and Minikube. The volume is created using dynamic volume provisioning. A number of [par
Fix the "no newline at end of file" warning.

2021-02-08 14:35 UTC, juan131 commented on immutable_tags_intro.md.erb
> +Bitnami will release a new chart updating its containers if a new version of the main container, significant changes, or critical vulnerabilities exist. [Learn more about Bitnami's policy on open CVE
Fix the "no newline at end of file" warning.

2021-02-08 14:35 UTC, juan131 commented on charts/wordpress/_use_external_database.md.erb
> +[Refer to the container documentation for more information](https://github.com/bitnami/bitnami-docker-wordpress#connect-wordpress-docker-container-to-an-existing-database).
Fix the "no newline at end of file" warning.

2021-02-08 14:35 UTC, juan131 commented on charts/wordpress/_understand_htaccess.md.erb
> +    htaccessPersistenceEnabled=true
Fix the "no newline at end of file" warning.

2021-02-08 14:35 UTC, juan131 commented on charts/wordpress/_understand_chart_persistence.md.erb
> +PersistenceVolumeClaims (PVCs) are used to keep the data across deployments. This is known to work in GCE, AWS, and Minikube. The volume is created using dynamic volume provisioning. A number of [par
It's worth to mention here that to scale WP "ReadWriteMany" volumes are needed. See:
- https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L188
- https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

2021-02-08 15:31 UTC, beltran-rubo commented on charts/mariadb/_configure_use_init_containers.md.erb
> +If additional containers are needed in the same pod as MariaDB, they can be defined using the *initContainers* parameter. Here is an example:
In addition to that, would be possible to add an example when that is useful? @juan131 any ideas for that example?

2021-02-08 15:31 UTC, beltran-rubo commented on charts/mariadb/_configure_use_sidecars.md.erb
> +If additional containers are needed in the same pod as MariaDB (such as additional metrics or logging exporters), they can be defined using the *sidecars* parameter. Here is an example:
I would mention the Helm Chart already includes sidecar containers for the Prometheus exporters, simply adding '--enable-metrics=true'. This would be for extra sidecar containers

2021-02-08 15:31 UTC, beltran-rubo commented on charts/wordpress/_add_repo.md.erb
> -title: Install the WordPress chart
I think this section should be generic for all the charts and reuse the same section for all of them. not needed to create the same one though

2021-02-08 15:31 UTC, beltran-rubo commented on charts/wordpress/_configure_use_sidecars.md.erb
> +id: configure_use_sidecars
Similar feeling for initContainers & sidecar containers. I think we should use the same section for all Charts, all of them include this 'optional' feature the users can use and it is not needed to use specific cases per solution though

2021-02-08 15:31 UTC, beltran-rubo commented on charts/wordpress/_understand_chart_persistence.md.erb
> +PersistenceVolumeClaims (PVCs) are used to keep the data across deployments. This is known to work in GCE, AWS, and Minikube. The volume is created using dynamic volume provisioning. A number of [par
yep good point

2021-02-09 08:51 UTC, vikram-bitnami commented on charts/wordpress/_add_repo.md.erb
> -title: Install the WordPress chart
I think it might be difficult to do this because the deployment command in the content is different for each chart.

2021-02-09 08:55 UTC, vikram-bitnami commented on charts/wordpress/_configure_use_sidecars.md.erb
> +id: configure_use_sidecars
I did not see these sections in all the charts modified to date.

Sidecars section not seen in:
- Apache
- MySQL

Initcontainers section not seen in:
- Apache
- MySQL
- WordPress

I can convert these to common sections but should they be added in the above cases or not ie. were they omitted in the current chart READMEs by oversight or because those features are not supported in the above charts?

2021-02-09 09:11 UTC, vikram-bitnami commented on charts/wordpress/_configure_use_sidecars.md.erb
> +id: configure_use_sidecars
In any case, I agree these can be common. I will implement this in a separate branch (based on your reply above) to avoid confusing this branch.

2021-02-09 09:11 UTC, vikram-bitnami commented
@beltran-rubo @juan131 please review this again.

2021-02-11 15:16 UTC, beltran-rubo approved these changes

2021-02-11 15:16 UTC, beltran-rubo commented on charts/mariadb/_add_repo.md.erb
> +* Deploy the WordPress chart with the following command:
This should say Mariadb

2021-02-12 07:22 UTC, merged